// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8IKQCtSub2cMmP8YdUfqf93wK31fTCEI',
    appId: '1:690218005733:web:d12d6dfa4333dc4510900c',
    messagingSenderId: '690218005733',
    projectId: 'g-shop-5b421',
    authDomain: 'g-shop-5b421.firebaseapp.com',
    databaseURL: 'https://g-shop-5b421-default-rtdb.firebaseio.com',
    storageBucket: 'g-shop-5b421.appspot.com',
    measurementId: 'G-XWX3TNRQKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoVx4CO4HdzET09BoAvzINGVwfbxqLuRA',
    appId: '1:690218005733:android:ae59d7dabca5a8fb10900c',
    messagingSenderId: '690218005733',
    projectId: 'g-shop-5b421',
    databaseURL: 'https://g-shop-5b421-default-rtdb.firebaseio.com',
    storageBucket: 'g-shop-5b421.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtlm9jENYCvF8d8nhzgIcRuV9FwincpTw',
    appId: '1:690218005733:ios:e4db13f410badeda10900c',
    messagingSenderId: '690218005733',
    projectId: 'g-shop-5b421',
    databaseURL: 'https://g-shop-5b421-default-rtdb.firebaseio.com',
    storageBucket: 'g-shop-5b421.appspot.com',
    iosClientId: '690218005733-tijor2fsmq8hkcmrnc2o94t8at8fuka1.apps.googleusercontent.com',
    iosBundleId: 'com.example.gshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtlm9jENYCvF8d8nhzgIcRuV9FwincpTw',
    appId: '1:690218005733:ios:e4db13f410badeda10900c',
    messagingSenderId: '690218005733',
    projectId: 'g-shop-5b421',
    databaseURL: 'https://g-shop-5b421-default-rtdb.firebaseio.com',
    storageBucket: 'g-shop-5b421.appspot.com',
    iosClientId: '690218005733-tijor2fsmq8hkcmrnc2o94t8at8fuka1.apps.googleusercontent.com',
    iosBundleId: 'com.example.gshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8IKQCtSub2cMmP8YdUfqf93wK31fTCEI',
    appId: '1:690218005733:web:96705997e82e192d10900c',
    messagingSenderId: '690218005733',
    projectId: 'g-shop-5b421',
    authDomain: 'g-shop-5b421.firebaseapp.com',
    databaseURL: 'https://g-shop-5b421-default-rtdb.firebaseio.com',
    storageBucket: 'g-shop-5b421.appspot.com',
    measurementId: 'G-0M670SG2TF',
  );

}